workspace: {}

packages:
  - "packages/*"
  - "examples/*"

catalog:
  # Core dependencies versions
  typescript: ^5.0.0
  "@types/node": ^20.0.0
  
  # Build tools
  tsup: ^8.0.0
  vitest: ^1.0.0
  
  # AST parsing
  "@typescript-eslint/typescript-estree": ^6.0.0
  "@babel/parser": ^7.23.0
  "@babel/traverse": ^7.23.0
  "@babel/types": ^7.23.0
  
  # ICU parsing
  intl-messageformat-parser: ^8.0.0
  
  # CLI tools
  commander: ^11.0.0
  chalk: ^5.3.0
  ora: ^7.0.1
  
  # File handling
  globby: ^14.0.0
  fast-glob: ^3.3.0
  
  # SARIF and reporting
  "@microsoft/sarif-builder": ^3.0.0
  
  # VS Code extension
  vscode: ^1.1.37