name: "Welcome new sponsor"
on:
  sponsorship:
    types: [created]
jobs:
  thank:
    runs-on: ubuntu-latest
    steps:
      - name: Thank new sponsor
        uses: actions/github-script@v7
        with:
          script: |
            const sponsor = context.payload.sponsorship?.sponsor?.login;
            const tier = context.payload.sponsorship?.tier?.name;
            if (!sponsor) return;
            const issueTitle = `🙏 Merci @${sponsor} — Bienvenue !`;
            const issueBody = [
              `Merci @${sponsor} d'avoir sponsorisé le projet (palier: ${tier || 'n/a'}).`,
              '',
              '- Rejoindre le salon “Sponsors”: <lien Discord/Discussion>',
              '- Indiquez vos besoins via le template “Sponsor priority request”.',
              '',
              '_Ticket créé automatiquement; vous pouvez le fermer._'
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['sponsor', 'automated']
            });